### PR TITLE
Motion Sensor support

### PR DESCRIPTION
**Pull request by MeesMaas**
Awesome library. Tested this one locally and it works. Not sure about the timeout. Could be one minute perhaps. Could not find any documentation about the timeout on the motion sensor.

### CODE REVIEW

**Comment by MeesMaas** [comment]
@zlinoliver would you be able to check this PR?

**Comment by talrhv** [comment]
> Awesome library. Tested this one locally and it works. Not sure about the timeout. Could be one minute perhaps. Could not find any documentation about the timeout on the motion sensor.

Hi, I checked your code with my pir and it seems to work good. great jobs!

https://www.aliexpress.com/item/1005002419717912.html?spm=a2g0o.productlist.0.0.475f360dJtEv7U&algo_pvid=c923ce6c-5aeb-45e0-868c-60c82cd95cb4&aem_p4p_detail=20211215085555546473794290000021813031&algo_exp_id=c923ce6c-5aeb-45e0-868c-60c82cd95cb4-9&pdp_ext_f=%7B%22sku_id%22%3A%2212000020588640664%22%7D

**Comment by IonutMindrescu** [comment]
Hi @MeesMaas , any updates on this one?

**Review by IonutMindrescu — APPROVED** [review]

**Comment by MeesMaas** [comment]
hi @IonutMindrescu. The code is done. So I suppose it is ready to merge? The checks are failing but I don't understand why because there is no privacy vulnerability. What do I need to do in order to get the check to succeed?

**Pull request closed without merging**
