### PR TITLE
fix functions fetch

### PR DESCRIPTION
**Pull request by lodev09**

### CODE REVIEW

**Comment by Hanh94** [comment]
@lodev09 Thank you very much for your kind feedback.
one device ID in the "devices"
Functions data are as follows：
 `{
    "result":[
        {
            "category":"fs",
            "devices":[
                "6cb2c761afc1e455d3rakk"
            ],
            "functions":Array[2],
            "product_id":"ybznohgystymcfpt"
        },
        {
            "category":"kj",
            "devices":[
                "12228800840d8e62ef5a"
            ],
            "functions":Array[4],
            "product_id":"xbwu1pxknjob6ca7"
        },
        {
            "category":"cl",
            "devices":[
                "vdevo162202171518573"
            ],
            "functions":Array[10],
            "product_id":"lhcosaeuwqlcf5kw"
        },
        Object{...},
        Object{...},
        Object{...},
        Object{...},
        Object{...},`

**Comment by lodev09** [comment]
@Hanh94 yep this is a bug for `_v2` codes. When I tested this prior to the dynamic hb update, this method returns "undefined" functions resulting to other devices not having the "functions" property.

**Comment by Hanh94** [comment]
> @Hanh94 yep this is a bug for `_v2` codes. When I tested this prior to the dynamic hb update, this method returns "undefined" functions resulting to other devices not having the "functions" property.

Products need to be standardized before there are standard instructions and standard status. We will query that problem and require you to provide the device ID that returns functions null

**Comment by Hanh94** [comment]
Hi @lodev09 , Thank you for your PR.
we believe we have solved your problem in the latest version, we will close this PR first, if there is any problem, please contact us anytime, thanks again.

**Pull request closed without merging**
